# MDIS for Linux project makefile
ifndef MEN_LIN_DIR
MEN_LIN_DIR = $(shell pwd)
endif

# You need to select the development environment so that MDIS
# modules are compiled with the correct tool chain

WIZ_CDK = Other

# All binaries (modules, programs and libraries) will be
# installed under this directory.

# TARGET_TREE

# The directory of the kernel tree used for your target's
# kernel. If you're doing selfhosted development, it's
# typically /usr/src/linux. This directory is used when
# building the kernel modules.

ifndef LIN_KERNEL_DIR
LIN_KERNEL_DIR = ${STAGING_KERNEL_DIR}
endif

# Defines whether to build MDIS to support RTAI. If enabled,
# MDIS modules support RTAI in addition to the standard Linux
# mode. Set it to "yes" if you want to access MDIS devices from
# RTAI applications

MDIS_SUPPORT_RTAI = no

# The directory where you have installed the RTAI distribution
# via "make install"

# RTAI_DIR

# The include directory used when building user mode libraries
# and applications. If you're doing selfhosted development,
# it's typically /usr/include. If you're doing cross
# development, select the include directory of your cross
# compiler. Leave it blank if your compiler doesn't need this
# setting.

# LIN_USR_INC_DIR

# Define whether to build/use static or shared user state
# libraries. In "static" mode, libraries are statically linked
# to programs. In "shared" mode, programs dynamically link to
# the libraries. "shared" mode makes programs smaller but
# requires installation of shared libraries on the target

LIB_MODE = shared

# Defines whether to build and install the release (nodbg) or
# debug (dbg) versions of the kernel modules. The debug version
# of the modules issue many debug messages using printk's for
# trouble shooting

ALL_DBGS = nodbg

# The directory in which the kernel modules are to be
# installed. Usually this is the target's
# /lib/modules/$(LINUX_VERSION)/misc directory.

ifndef MODS_INSTALL_DIR
MODS_INSTALL_DIR = ${D}/lib/modules/$(LINUX_VERSION)/misc
endif

# The directory in which the user state programs are to be
# installed. Often something like /usr/local/bin. (relative to
# the target's root tree)

ifndef BIN_INSTALL_DIR
BIN_INSTALL_DIR = ${D}${bindir}
endif

# The directory in which the shared (.so) user mode libraries
# are to be installed. Often something like /usr/local/lib.
# (relative to the target's root tree)

ifndef LIB_INSTALL_DIR
LIB_INSTALL_DIR = ${D}${libdir}
endif

# The directory in which the static user mode libraries are to
# be installed. Often something like /usr/local/lib on
# development host. For cross compilation select a path
# relative to your cross compilers lib directory.

ifndef STATIC_LIB_INSTALL_DIR
STATIC_LIB_INSTALL_DIR = ${D}${libdir}
endif

# The directory in which the MDIS descriptors are to be
# installed. Often something like /etc/mdis. (Relative to the
# targets root tree)

ifndef DESC_INSTALL_DIR
DESC_INSTALL_DIR = ${D}${sysconfdir}mdis
endif

# The directory in which the MDIS device nodes are to be
# installed. Often something like /dev. (Relative to the
# targets root tree)

DEVNODE_INSTALL_DIR = /dev

ALL_LL_DRIVERS = \
	XM01BC/DRIVER/COM/driver.mak \
	SMB2/DRIVER/COM/driver.mak \
	ICANL2/DRIVER/COM/driver.mak \
	MMODPRG/DRIVER/COM/driver.mak \
	MMODPRG/DRIVER/COM/driver_4k.mak \
	Z017/DRIVER/COM/driver.mak \
	MSCAN/DRIVER/COM/driver_z15.mak \
	M033/DRIVER/COM/driver.mak \
	M047/DRIVER/COM/driver.mak

ALL_BB_DRIVERS = \
	SMB2BB/DRIVER/NATIVE/driver.mak \
	D203/DRIVER/COM/driver_a24.mak \
	CHAMELEON/DRIVER/COM/driver_pcitbl.mak \
	D203/DRIVER/COM/driver.mak

ALL_USR_LIBS = \
	USR_OSS/library.mak \
	USR_UTL/COM/library.mak \
	SMB2_API/COM/library.mak \
	SMB2_BMC_API/COM/library.mak \
	SMB2_SHC/COM/library.mak \
	ICANL2_API/COM/library.mak \
	MSCAN_API/COM/library.mak

ALL_CORE_LIBS = \
	DBG/library.mak \
	OSS/library.mak \
	CHAMELEON/COM/library.mak \

ALL_LL_TOOLS = \
	XM01BC/TOOLS/XM01BC_CTRL/COM/program.mak \
	SMB2/EXAMPLE/SMB2_SIMP/COM/program.mak \
	SMB2/EXAMPLE/SMB2_F601/COM/program.mak \
	SMB2/TOOLS/SMB2_CTRL/COM/program.mak \
	SMB2/TOOLS/SMB2_BOARDIDENT/COM/program.mak \
	SMB2/TOOLS/SMB2_TOUCH/COM/program.mak \
	SMB2/TOOLS/SMB2_BMC_CTRL/COM/program.mak \
	SMB2/TOOLS/SMB2_SHC_CTRL/COM/program.mak \
	SMB2/TOOLS/SMB2_STM32_FLASH/COM/program.mak \
	SMB2/TOOLS/SMB2_EETEMP/COM/program.mak \
	SMB2/TOOLS/SMB2_POE/COM/program.mak \
	ICANL2/EXAMPLE/ICANL2_SIMP/COM/program.mak \
	ICANL2/EXAMPLE/ICANL2_CYC/COM/program.mak \
	ICANL2/EXAMPLE/ICANL2_SIGNAL/COM/program.mak \
	ICANL2/TEST/ICANL2_VERI/COM/program.mak \
	Z017/EXAMPLE/Z17_SIMP/COM/program.mak \
	Z017/TOOLS/Z17_IO/COM/program.mak \
	Z017/TOOLS/Z127_IO/COM/program.mak \
	Z017/TOOLS/Z127_IN/COM/program.mak \
	Z017/TOOLS/Z127_OUT/COM/program.mak \
	MSCAN/TOOLS/MSCAN_ALYZER/COM/program.mak \
	MSCAN/TOOLS/MSCAN_LOOPB/COM/program.mak \
	MSCAN/TOOLS/MSCAN_MENU/COM/program.mak \
	MSCAN/TOOLS/MSCAN_PINGPONG/COM/program.mak \
	M033/EXAMPLE/M33_DEMO/COM/program.mak \
	M033/EXAMPLE/M33_EX1/COM/program.mak \
	M047/EXAMPLE/M47_SIMP/COM/program.mak \
	M047/TOOLS/M47_TOOL/COM/program.mak

ALL_COM_TOOLS = \
	MDIS_API/M_ERRSTR/COM/program.mak \
	MDIS_API/M_GETBLOCK/COM/program.mak \
	MDIS_API/M_GETSTAT/COM/program.mak \
	MDIS_API/M_GETSTAT_BLK/COM/program.mak \
	MDIS_API/M_MOD_ID/COM/program.mak \
	MDIS_API/M_OPEN/COM/program.mak \
	MDIS_API/M_READ/COM/program.mak \
	MDIS_API/M_REV_ID/COM/program.mak \
	MDIS_API/M_SETBLOCK/COM/program.mak \
	MDIS_API/M_SETSTAT/COM/program.mak \
	MDIS_API/M_SETSTAT_BLK/COM/program.mak \
	MDIS_API/M_WRITE/COM/program.mak \
	WDOG/WDOG_TEST/COM/program.mak \
	WDOG/WDOG_SIMP/COM/program.mak \

ALL_NATIVE_DRIVERS = \
	DRIVERS/M077/DRIVER/driver.mak \
	DRIVERS/13Z025/driver.mak \
	DRIVERS/CHAMELEON/driver.mak \
	DRIVERS/Z069_RST_WDG/driver.mak

ALL_NATIVE_LIBS =

ALL_NATIVE_TOOLS =

ALL_DESC = system

include $(MEN_LIN_DIR)/BUILD/MDIS/TPL/rules.mak

